services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8000
      - VITE_API_BASE_URL=/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - redis
      - db
    profiles: ["dev"]

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver
      - CB_ADMIN_NAME=admin
      - CB_ADMIN_PASSWORD=admin
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    depends_on:
      - db
    profiles: ["dev"]

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      - ENV=dev
      - ENABLE_DOCS=true
      - API_PREFIX=/api
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SECRET_KEY=dev-secret
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    profiles: ["dev"]

volumes:
  db_data:
  redis_data:
  cloudbeaver_workspace:
