site_name: FastAPI Auth Skeleton
repo_url: https://example.com/your-repo
theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
nav:
  - Введение: index.md
  - Быстрый старт: setup.md
  - Авторизация: auth.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

